//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public byte[] FileContent { get; set; }
        public string UserId { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual Modules Modules { get; set; }
    }
}
