// <auto-generated />
namespace LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeuseridfrominttostringindocuments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeuseridfrominttostringindocuments));
        
        string IMigrationMetadata.Id
        {
            get { return "201807310920070_change userid from int to string in documents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
