// <auto-generated />
namespace LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeuseridvaluetononnullableandsetthevalidationfornametoberequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeuseridvaluetononnullableandsetthevalidationfornametoberequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201807302037374_change userid value to non nullable and set the validation for name to be required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
